Default: &defaults
  user: Scriptoria
  password: Scriptoria
  host: localhost
  port: 5432
  database: Scriptoria
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Scriptoria_test
  <<: *defaults

Staging:
  database: Scriptoria_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Scriptoria_production
  poolsize: 100
  <<: *defaults
