Default: &defaults
  user: scriptorium
  password: scriptorium
  host: localhost
  port: 5432
  database: scriptorium
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: scriptorium_test
  <<: *defaults

Staging:
  database: scriptorium_staging
  poolsize: 100
  <<: *defaults

Production:
  database: scriptorium_production
  poolsize: 100
  <<: *defaults
